INSERT INTO TIPO_EMPRENDIMIENTO(ID_TIPO_EMPRENDIMIENTO, NOMBRE) 
VALUES (1,'Ventas Habituales');
INSERT INTO TIPO_EMPRENDIMIENTO(ID_TIPO_EMPRENDIMIENTO, NOMBRE) 
VALUES (2,'Grupo Emprendedor');

INSERT INTO ESTADO_EMPRENDIMIENTO(ID_ESTADO_EMPRENDIMIENTO, NOMBRE)
VALUES (1, 'Activo');
INSERT INTO ESTADO_EMPRENDIMIENTO(ID_ESTADO_EMPRENDIMIENTO, NOMBRE)
VALUES (2, 'Inactivo');