CREATE TABLE IF NOT EXISTS TIPO_EMPRENDIMIENTO(
    ID_TIPO_EMPRENDIMIENTO NUMERIC,
    NOMBRE VARCHAR(30),
    PRIMARY KEY (ID_TIPO_EMPRENDIMIENTO)
);

CREATE TABLE IF NOT EXISTS ESTADO_EMPRENDIMIENTO(
    ID_ESTADO_EMPRENDIMIENTO NUMERIC,
    NOMBRE VARCHAR(30),
    PRIMARY KEY (ID_ESTADO_EMPRENDIMIENTO)
);

CREATE TABLE IF NOT EXISTS EMPRENDIMIENTO (
    ID_EMPRENDIMIENTO NUMERIC,
    NOMBRE VARCHAR(30),
    DESCRIPCION VARCHAR(100),
    IMAGEN VARCHAR(30),
    HORARIOS VARCHAR(30),  
    ID_TIPO NUMERIC,
	ID_ESTADO NUMERIC,
    PRIMARY KEY (ID_EMPRENDIMIENTO),
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_EMPRENDIMIENTO (ID_TIPO_EMPRENDIMIENTO),
	FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_EMPRENDIMIENTO (ID_ESTADO_EMPRENDIMIENTO)
);


CREATE TABLE IF NOT EXISTS ESTADO_PRODUCTO(
    ID_ESTADO_PRODUCTO NUMERIC,
    NOMBRE VARCHAR(30),
    PRIMARY KEY (ID_ESTADO_PRODUCTO)
);

CREATE TABLE IF NOT EXISTS PRODUCTO (
    ID_PRODUCTO NUMERIC,
    NOMBRE VARCHAR(30),
    PRECIO FLOAT,
    DESCRIPCION VARCHAR(100),
    IMAGEN VARCHAR(30),
    ID_ESTADO_PRODUCTO NUMERIC, 
    PRIMARY KEY (ID_PRODUCTO),
    FOREIGN KEY (ID_ESTADO_PRODUCTO) REFERENCES ESTADO_PRODUCTO (ID_ESTADO_PRODUCTO)
);

CREATE TABLE IF NOT EXISTS USUARIO(
    ID_USUARIO NUMERIC,
    NOMBRE VARCHAR(30),
    ID VARCHAR(10),
    CONTRASEÑA VARCHAR(10),
    PRIMARY KEY (ID_USUARIO, ID)
);

CREATE TABLE IF NOT EXISTS EMPRENDEDOR(
    ID_EMPRENDEDOR NUMERIC,
    PRIMARY KEY (ID_EMPRENDEDOR)
);